Revert "wrlinux-exclude-from-world: remove wr-coverageagent"
This reverts commit dd5c4974e448eeae8856769415a43f8856bb427a.

Still fails many world builds with this error:
   xml/y.tab.c: In function 'STparse':
   xml/y.tab.c:64:25:
      error: too few arguments to function 'STlex'
      #define yylex           STlex

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>