rpm: provide elf.h for native builds
Issue: LIN7-3260

rpm-native builds will use the host elf.h file because we do
not routinely install one in our sysroot.  This is dangerous,
so we supply our own version taken from our glibc.

This avoids errors like --
Unhandled relocation 258 in .debug_info section
ERROR: Function fialed: split_and_strip_files

Signed-off-by: Joe Slater <jslater@windriver.com>